_welcome:
    pattern:  /
    defaults: { _controller: CoreBundle:Welcome:index }

_topics:
    resource: "@CoreBundle/Controller/TopicsController.php"
    type:     annotation
    prefix:   /topics

_users:
    resource: "@CoreBundle/Controller/UsersController.php"
    type:     annotation
    prefix:   /users

_main:
    resource: routing.yml
