_welcome:
    pattern:  /
    defaults: { _controller: CoreBundle:Welcome:index }

_registration:
    pattern:  /register/
    defaults: { _controller: CoreBundle:Welcome:register }

_login:
    pattern:  /login/
    defaults: { _controller: CoreBundle:Welcome:login }

_logout:
    pattern:  /logout/
    defaults: { _controller: CoreBundle:Welcome:logout }

_topics:
    resource: "@CoreBundle/Controller/TopicsController.php"
    type:     annotation
    prefix:   /topics

_users:
    resource: "@CoreBundle/Controller/UsersController.php"
    type:     annotation
    prefix:   /users

_categories:
    resource: "@CoreBundle/Controller/CategoriesController.php"
    type:     annotation
    prefix:   /categories

_main:
    resource: routing.yml